### ISSUE TITLE
2021.05.22

### ISSUE THREAD

**Issue by AMYMEME** [JXS2021-CUBE/mail-cube-server#2]
## TODO

- [x] ORM 객체 만들기
- [x] 양식 목록 불러오기 (`GET /templates`)
- [x] 양식 내용 불러오기 (`GET /templates/{tid}`)
- [x] 양식 추가 (`POST /templates`)
- [x] 양식 수정 (`PUT /templates/{id}`)
- [x] 양식 삭제 (`DELETE /templates/{id}`)
- [x] 파일 업로드 및 DB에 링크 저장 
- [x] azure에서 api로 spring boot에 파일 불러오기
- [x] Parsing하기
- [x] 이메일 전송하기 
- [x] Azure 앱 인스턴스 배포하기
